### ISSUE TITLE
Spring softlock

### ISSUE THREAD

**Issue by AngrySonics** [NicholasRickys/Nicks-Tower-of-Pizza-Pack#2]
Happens in any stage with horizontal yellow/red springs (yes, i've tested GFZ1 and GFZ2). This seems to only happen when the player is not Mach Running.

![Footage of this softlock happening in GFZ1](https://github.com/NicholasRickys/Nicks-Tower-of-Pizza-Pack/assets/112799592/4015a8d4-b4ce-4768-a577-4c2332f222f4)

**Comment by Saxashitter** [comment]
known, fixed in not public builds
